"""Add origin fields to isolado

Revision ID: 2001ef613611
Revises: 
Create Date: 2025-11-07 12:43:47.729864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2001ef613611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('isolado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_tipo', sa.String(length=20), nullable=False, server_default='coleta'))
        batch_op.add_column(sa.Column('origem_instituicao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('especie_nome_cientifico', sa.String(length=200), nullable=True))

    with op.batch_alter_table('isolado', schema=None) as batch_op:
        batch_op.alter_column('origem_tipo', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('isolado', schema=None) as batch_op:
        batch_op.alter_column('coleta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('origem_instituicao')
        batch_op.drop_column('origem_tipo')

    # ### end Alembic commands ###
