"""Add isolates origin and species fields

Revision ID: e2007977e573
Revises: 2001ef613611
Create Date: 2025-11-07 14:29:09.913371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2007977e573'
down_revision = '2001ef613611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('isolado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especie_nome_cientifico', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('isolado', schema=None) as batch_op:
        batch_op.drop_column('especie_nome_cientifico')

    # ### end Alembic commands ###
